[package]
org = "ballerina"
name = "ldap"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "auth"
version = "@stdlib.auth.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[platform.java11.dependency]]
path = "../ldap-native/build/libs/ldap-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "ldap"
version = "@project.version@"
