[package]
org = "ballerina"
name = "auth"
version = "1.0.4"

[[dependency]]
org = "ballerina"
name = "cache"
version = "2.0.4"

[[dependency]]
org = "ballerina"
name = "config"
version = "1.0.4"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.0.4"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.0.4"

[[dependency]]
org = "ballerina"
name = "stringutils"
version = "0.5.4"

[[platform.java11.dependency]]
path = "../auth-native/build/libs/auth-native-1.0.4-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "auth"
version = "1.0.4-SNAPSHOT"
