[package]
org = "ballerina"
name = "auth"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../auth-native/build/libs/auth-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "auth"
version = "@project.version@"
