[[auth.users]]
username="peter"
password="plain-password"
scopes=["update", "write"]

[[auth.users]]
username="alice"
password="@encrypted:{THCD5ftXj0duD7A+4NMRbtDRQhabekLtcWfYEL2SoHM=}"
scopes=["read", "write"]

[[auth.users]]
username="bob"
password="@encrypted:{mLOinYNLvo15S+Xgq/Z93jrzLSFJWVYOpGnWloXLIMg=}"
scopes=["read"]

[[auth.users]]
username="hashedSha256"
password="@sha256:{cd2eb0837c9b4c962c22d2ff8b5441b7b45805887f051d39bf133b583baf6860}"
scopes=["read"]

[[auth.users]]
username="hashedSha384"
password="@sha384:{1249e15f035ed34786a328d9fdb2689ab24f7c7b253d1b7f66ed92a679d663dd502d7beda59973e8c91a728b929fc8cd}"
scopes=["read"]

[[auth.users]]
username="hashedSha512"
password="@sha512:{9057ff1aa9509b2a0af624d687461d2bbeb07e2f37d953b1ce4a9dc921a7f19c45dc35d7c5363b373792add57d0d7dc41596e1c585d6ef7844cdf8ae87af443f}"
scopes=["read"]
